// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ztkasl_mG7ENx1uRYMJdUB1jnGA6gf4',
    appId: '1:900091830031:web:dc0d2843d8e280b531287a',
    messagingSenderId: '900091830031',
    projectId: 'musicapp-7aabf',
    authDomain: 'musicapp-7aabf.firebaseapp.com',
    storageBucket: 'musicapp-7aabf.firebasestorage.app',
    measurementId: 'G-S8PKS8R5GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxm1ram1zZ_tUFSuKUo_IPCjnEYdtpEZ4',
    appId: '1:900091830031:android:8cc662ca7868f18831287a',
    messagingSenderId: '900091830031',
    projectId: 'musicapp-7aabf',
    storageBucket: 'musicapp-7aabf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXx5WmY0it1vf_vHgXhhJvy_2EoqC08Dc',
    appId: '1:900091830031:ios:87ad49d0f87ab3b531287a',
    messagingSenderId: '900091830031',
    projectId: 'musicapp-7aabf',
    storageBucket: 'musicapp-7aabf.firebasestorage.app',
    iosBundleId: 'littletech.com.littleMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXx5WmY0it1vf_vHgXhhJvy_2EoqC08Dc',
    appId: '1:900091830031:ios:87ad49d0f87ab3b531287a',
    messagingSenderId: '900091830031',
    projectId: 'musicapp-7aabf',
    storageBucket: 'musicapp-7aabf.firebasestorage.app',
    iosBundleId: 'littletech.com.littleMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ztkasl_mG7ENx1uRYMJdUB1jnGA6gf4',
    appId: '1:900091830031:web:d058b0d7f585117131287a',
    messagingSenderId: '900091830031',
    projectId: 'musicapp-7aabf',
    authDomain: 'musicapp-7aabf.firebaseapp.com',
    storageBucket: 'musicapp-7aabf.firebasestorage.app',
    measurementId: 'G-07G0RGN4FG',
  );
}
